export const tasks = [
  {
    id: "1",
    title: "Do Laundry",
    description: "DO all the laundry including the neighbors",
    date: "January 30, 2024",
    time: "11:00 am",
    isDone: "yes",
  },
  {
    id: "2",
    title: "Grocery Shopping",
    description: "Pick up essentials and fresh produce",
    date: "January 31, 2024",
    time: "3:00 pm",
    isDone: "no",
  },
  {
    id: "3",
    title: "Workout Session",
    description: "Hit the gym for a revitalizing workout",
    date: "February 1, 2024",
    time: "8:00 am",
    isDone: "no",
  },
  {
    id: "4",
    title: "Meeting with Team",
    description: "Discuss upcoming projects and deadlines",
    date: "February 2, 2024",
    time: "2:30 pm",
    isDone: "no",
  },
  {
    id: "5",
    title: "Read a Book",
    description: "Dive into a captivating novel or educational read",
    date: "February 3, 2024",
    time: "7:00 pm",
    isDone: "no",
  },
  {
    id: "6",
    title: "Family Dinner",
    description: "Enjoy a cozy dinner with loved ones",
    date: "February 4, 2024",
    time: "6:30 pm",
    isDone: "no",
  },
  {
    id: "7",
    title: "Plan Weekend Getaway",
    description: "Research and plan for an upcoming weekend trip",
    date: "February 5, 2024",
    time: "10:00 am",
    isDone: "no",
  },
  {
    id: "8",
    title: "Complete Work Presentation",
    description: "Finalize and polish the upcoming presentation",
    date: "February 6, 2024",
    time: "1:00 pm",
    isDone: "no",
  },
  {
    id: "9",
    title: "Creative Writing Session",
    description: "Express yourself through a creative writing session",
    date: "February 7, 2024",
    time: "4:30 pm",
    isDone: "no",
  },
  {
    id: "10",
    title: "Yoga and Meditation",
    description: "Relax and rejuvenate with a yoga and meditation session",
    date: "February 8, 2024",
    time: "9:00 am",
    isDone: "no",
  },
  {
    id: "11",
    title: "Networking Event",
    description: "Attend a networking event to expand connections",
    date: "February 9, 2024",
    time: "6:00 pm",
    isDone: "no",
  },
  {
    id: "12",
    title: "Cooking Class",
    description: "Learn new culinary skills in a cooking class",
    date: "February 10, 2024",
    time: "5:30 pm",
    isDone: "no",
  },
  {
    id: "13",
    title: "Gardening Session",
    description: "Tend to the garden and plant new flowers",
    date: "February 11, 2024",
    time: "11:30 am",
    isDone: "no",
  },
  {
    id: "14",
    title: "Movie Night",
    description: "Enjoy a movie night with friends or family",
    date: "February 12, 2024",
    time: "8:00 pm",
    isDone: "no",
  },
  {
    id: "15",
    title: "Tech Workshop",
    description: "Participate in a workshop to enhance technical skills",
    date: "February 13, 2024",
    time: "2:00 pm",
    isDone: "no",
  },
];
